### ISSUE TITLE
Does not support swin-transformer?

### ISSUE THREAD

**Issue by YoloEliwa** [facebookresearch/ToMe#15]
Hello,
Thanks for this amazing work!
When I use tome, I found it doesn't seem to support swin-transformer.I want to know why it is not supported and whether it be supported in the future?

I am looking forward to your reply!

**Comment by dbolya** [comment]
Hi, thanks for you interest.

We do not currently support Swin and have no plans on doing so in the future. Swin's shifted window attention is complicated and it would be hard to get much speed benefit because of that.
