### ISSUE TITLE
eucl distance function in Tab. 1b

### ISSUE THREAD

**Issue by ChenMnZ** [facebookresearch/ToMe#19]
Hello,
Thank you for your interesting work!

I want to know the implementation of eucl distance function in Tab. 1b. I try to use `scores = torch.cdist(a,b)`  to calculate the eucl distance, but the top-1 accuracy on ViT-L/16 with r=8  is only 61.50 by my implementation.

Thanks!

**Comment by dbolya** [comment]
Hi, thanks for your interest!

A couple of things:
 - Make sure metrics isn't normalized beforehand. Normalization is there to compute cosine similarity efficiently.
 - Euclidian distance is a _distance_ measure, not a similarity measure. So, you need to use `-torch.cdist(a,b)` instead.
 
 Of the top of my head, I can't think of anything else.

**Comment by ChenMnZ** [comment]
Thanks! I have successfully reproduced.
