### ISSUE TITLE
I keep getting this issue, how do I fix it?

### ISSUE THREAD

**Issue by 303Aki303** [facebookresearch/ToMe#26]
raise NotImplementedError(f"Invalid/unsupported device. Expected `cpu`, `cuda`, or `mps`, got {device.type}.")
NotImplementedError: Invalid/unsupported device. Expected `cpu`, `cuda`, or `mps`, got privateuseone.

**Comment by dbolya** [comment]
I believe you opened this issue in the wrong github. That line of code only appears in [tomesd](https://github.com/dbolya/tomesd). Can you move this issue over there. Thanks.
