### ISSUE TITLE
Does ToMe work for Restormer?

### ISSUE THREAD

**Issue by tttt-0814** [facebookresearch/ToMe#27]
Can I apply ToMe for Restormer ? (https://github.com/swz30/Restormer)

**Comment by dbolya** [comment]
You could probably do something similar to [tomesd](https://github.com/dbolya/tomesd/) since denoising/deblurring etc requires all the tokens to be in tact. But, it would probably require some extra effort to get working.

**Comment by tttt-0814** [comment]
I got it. Thanks.
