### ISSUE TITLE
Has anyone been able to successfully convert the timm+tome model to onnx?

### ISSUE THREAD

**Issue by Roman54228** [facebookresearch/ToMe#32]
Facing difficulties with onnx opset vesrions and operators used in this implementation, cant convert timm model to onnx. Is there a way to do it maybe in other way?

**Comment by dbolya** [comment]
You might be interested in this PR for tomesd: https://github.com/dbolya/tomesd/pull/43

**Comment by Roman54228** [comment]
Thanks you a lot!!! It worked
