### ISSUE TITLE
Only less similar tokens from Set A are concatenated as unmerged tokens?

### ISSUE THREAD

**Issue by DaiX01** [facebookresearch/ToMe#46]
![Snipaste_2024-09-28_21-11-51](https://github.com/user-attachments/assets/616665a6-44f4-4bcb-b24d-678a75374280)

Hi, I am confused about selecting unmerged tokens in 'bipartite_soft_matching'. Does this mean that only t1 (which is t//2) tokens are retained each time, where r are the ones after merging, and t1 - r are from Set A, while those from Set B are excluded? If I understand correctly, why is it set up this way?
Thanks for your help!

**Comment by dbolya** [comment]
Sets A and B are the `src` and `dst` sets you can see in the top of the merge function. The `unm` set is just the subset of the `src` (or set A) that did not get merged to anything in `dst` (or set B).

The number of tokens merged are `r`, so r tokens from `src` are merged into tokens from `dst`. Thus, `unm` contains the remainder (`t // 2 - r`) tokens that were not chosen to merge with `dst`--i.e., ones least similar to anything in `dst`.

The three indices (`unm_idx`, `src_idx`, `dst_idx`) denote the following groups in this picture:
![image](https://github.com/user-attachments/assets/331660fc-71d6-48d1-8b63-2edc9082bf0e)

**Comment by DaiX01** [comment]
I see now.  I mistakenly assumed there was a line 'dst = dst. gather(dim=-2, index=dst_idx. expand(n, r, c))', but it doesn’t actually exist.  Apologies for my oversight.  Thank you for your answer—excellent work and elegant code!
