### ISSUE TITLE
evaluate on ImageNet

### ISSUE THREAD

**Issue by WW2YW** [facebookresearch/ToMe#48]
Hello Author,

Thank you for your contributions !
I would like to ask if the code does not contain the .py file that directly evaluates on ImageNet?
If I want to write this code by myself, would you like to know if there are any pre-processing steps required to achieve the same results as in the paper? 
Thank you!

**Comment by dbolya** [comment]
Imagenet eval code is outside of the scope of this repo, but for preprocessing code check:
https://github.com/facebookresearch/ToMe/blob/main/examples/0_validation_timm.ipynb

**Comment by WW2YW** [comment]
Thank you so much for your clarification and the helpful link! I appreciate your guidance.
